### ISSUE TITLE
How to clear all filters

### ISSUE THREAD

**Issue by Bridua98** [eugener/oxbow#73]
I need to clear all columns filters before reload my JTable data. There are a way to do this?

**Comment by eugener** [comment]
Model changes on the data should reset it. Take a look at
https://github.com/eugener/oxbow/blob/1ed5881ba3fd38f7687744f7efab0d0e4c01f764/swingbits/src/main/java/org/oxbow/swingbits/table/filter/AbstractTableFilter.java#L75-L94

**Comment by blasferna** [comment]
I have the same question, I need to clear all filters programmatically like clicking **Clear all column filters** PopupWindow button because when clearing all model data the filters remain.

![image](https://user-images.githubusercontent.com/8385910/106648624-4a76b180-656f-11eb-8cdc-c3e78a487c22.png)

I tried clearing the data in different ways but the filters are still in the table.

**Comment by eugener** [comment]
I don't believe this functionality is exposed through API, even though it exists internally.
PRs are always welcome :)
